version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-beta_current_amd64.deb
            sudo dpkg -i google-chrome-beta_current_amd64.deb
            sudo apt-get -fy install
            echo 'export CHROME_PATH=/opt/google/chrome-beta/google-chrome-beta' >> $BASH_ENV
            source $BASH_ENV
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test