version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Chrome
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            rm google-chrome.deb
            echo 'export CHROME_PATH=/opt/google/chrome/google-chrome' >> $BASH_ENV
            source $BASH_ENV
      - run: yarn
      - run: yarn test